const languageStrings = {
  en: {
    translation: {
      WELCOME_MESSAGE: 'Welcome to New York Trivia! You can request a fun fact by saying "tell me a New York fact". If you need help with the phrases to interact with the skill, say "help". To stop, simply say "Cancel!"',
      HELP_MESSAGE: 'You can ask for a New York fact, phrases you can use include "tell me a fact about New York", "a curious fact about New York", "what is a fun fact about New York", "what is an interesting fact about New York", "tell me something about New York", "I want to hear a fact about New York". How can I help you?',
      GOODBYE_MESSAGE: 'Goodbye!',
      FALLBACK_MESSAGE: 'Sorry, I don\'t know about that. Please try again.',
      ERROR_MESSAGE: 'Sorry, there was an error. Please try again.',
      GET_FRASES_MSG: 'Here is a New York fact: ',
      Descripcion: 'New York, often called New York City (NYC) to distinguish it from the State of New York, is the most populous city in the United States. Known for its iconic landmarks like the Statue of Liberty, Times Square, and Central Park, it is a global hub for culture, finance, media, and entertainment. You can ask for another fun fact about New York by saying, "tell me a fun fact about New York" or if you need help with the phrases to interact with the skill, say "help". To stop, simply say "Cancel!"',
      LUGARES_TURISTICOS:'Times Square este es el corazón de la ciudad, famoso por sus carteles publicitarios y luces de neón. ¡No te pierdas la vista desde las escaleras rojas del TKTS!, Estatua de la Libertad: Es un símbolo histórico y una visita obligada. Puedes llegar en ferry desde Battery Park. Empire State Building: Sube a la cima para disfrutar de impresionantes vistas panorámicas de la ciudad. Central Park: Un oasis verde en medio de los rascacielos. Ideal para pasear, hacer un picnic o alquilar una bicicleta. Museo Metropolitano de Arte (Met): Uno de los museos más grandes del mundo, con una colección impresionante. Puente de Brooklyn: Cruza este icónico puente peatonal y disfruta de vistas espectaculares.' ,
      COMIDA: "Bagel with cream cheese: A classic New York breakfast item, bagels are dense, chewy, and typically topped with a generous spread of cream cheese. New York Cheesecake: This iconic dessert is rich and creamy, with a dense texture and a graham cracker crust. New York-style Pizza: Known for its thin, foldable crust and generous toppings, New York-style pizza is a beloved staple of the city's food scene. Bacon, egg, and cheese: A popular breakfast sandwich, typically served on a roll or bagel, and often enjoyed on-the-go. Pretzels: Soft, doughy pretzels are a common street food in New York, often enjoyed with mustard or cheese sauce.",
      TRAJE_TIPICO: 'Cowboy Style: The cowboy style is synonymous with ruggedness and practicality. Typically, it includes items like a wide-brimmed cowboy hat, a plaid or denim shirt, a leather belt with a large buckle, sturdy denim jeans, and cowboy boots. Accessories often include a bandana and sometimes spurs. This style is deeply rooted in the history of the American West and is still celebrated in rodeos and country music scenes. Urban Style in New York: The urban style in New York is diverse and ever-evolving, reflecting the city’s dynamic and eclectic culture. Common elements include designer sneakers, slim-fit jeans, graphic t-shirts, hoodies, and leather or denim jackets. Accessories often include stylish sunglasses, caps, and various forms of streetwear jewelry. This style is influenced by hip-hop culture, high fashion, and the city’s vibrant street life, making it a unique blend of comfort and high fashion.',
      PERSONAJES_SOBRESALIENTES: "Walt Whitman: He was an American poet, essayist, and journalist, considered one of the most influential writers in American literature. His most famous work is 'Leaves of Grass'. Henry James: He was an American-British novelist and literary critic, known for works such as 'The Portrait of a Lady' and 'The Turn of the Screw'. Robert De Niro: He is an American actor, director, and producer, celebrated for his roles in films like 'Taxi Driver', 'The Godfather Part II', and 'Raging Bull'. Al Pacino: He is an American actor and director, known for his performances in films such as 'The Godfather', 'Scarface', and 'Scent of a Woman'. Sojourner Truth: She was an African-American abolitionist and women's rights activist, famous for her speech 'Ain't I a Woman?'. Bella Abzug: She was an American lawyer, congresswoman, and social activist, known for her fight for women's rights and civil rights.",
      MUSICA: "Music of New York"
    }
  },
  es: {
    translation: {
      WELCOME_MESSAGE: 'Bienvenido a la skill de Nueva York! ',
      HELP_MESSAGE: 'Puedes pedir un dato sobre Nueva York, frases que puedes ocupar "cual es la descripcion de esta ciudad", "dame la descripcion de esta ciudad", "dame lugares turisticos para visitar", "lugares turisticos", "dame las comidas mas tipicas","dime las comidas tipicas", "personajes sobresalientes de new york". ¿Cómo te puedo ayudar?',
      GOODBYE_MESSAGE: '¡Gracias por usar New York! ¡Espero verte pronto!',
      FALLBACK_MESSAGE: 'Lo siento, no sé sobre eso. Por favor intenta de nuevo.',
      ERROR_MESSAGE: 'Lo siento, ha ocurrido un problema en la pronunciacion. Por favor, inténtalo de nuevo más tarde.',
      GET_FRASES_MSG: 'Aquí tienes un dato sobre Nueva York: ',
      Descripcion: 'Nueva York, a menudo llamada Ciudad de Nueva York (NYC) para distinguirla del Estado de Nueva York, es la ciudad más poblada de los Estados Unidos. Conocida por sus emblemáticos lugares como la Estatua de la Libertad, Times Square y Central Park, es un centro global de cultura, finanzas, medios y entretenimiento. Puedes pedir otro dato curioso de Nueva York diciendo, "dime un dato curioso sobre Nueva York" o si necesitas ayuda con las frases para interactuar con la skill, di "ayuda". Para detener, simplemente di "¡Cancelar!',
      LUGARES_TURISTICOS: 'Times Square este es el corazón de la ciudad, famoso por sus carteles publicitarios y luces de neón. ¡No te pierdas la vista desde las escaleras rojas del TKTS!, Estatua de la Libertad: Es un símbolo histórico y una visita obligada. Puedes llegar en ferry desde Battery Park. Empire State Building: Sube a la cima para disfrutar de impresionantes vistas panorámicas de la ciudad. Central Park: Un oasis verde en medio de los rascacielos. Ideal para pasear, hacer un picnic o alquilar una bicicleta. Museo Metropolitano de Arte (Met): Uno de los museos más grandes del mundo, con una colección impresionante. Puente de Brooklyn: Cruza este icónico puente peatonal y disfruta de vistas espectaculares.',
      COMIDA: "Bagel con queso crema: Un clásico del desayuno neoyorquino, los bagels son densos, masticables y generalmente se cubren con una generosa capa de queso crema. Tarta de queso New York: Este postre icónico es rico y cremoso, con una textura densa y una base de galleta graham. Pizza al estilo neoyorquino: Conocida por su corteza delgada y plegable y sus abundantes ingredientes, la pizza al estilo neoyorquino es un alimento básico y querido en la escena culinaria de la ciudad. Bacon, huevo y queso: Un popular sándwich de desayuno, típicamente servido en un bollo o bagel, y a menudo disfrutado mientras se va de un lugar a otro. Pretzels: Los pretzels suaves y esponjosos son una comida común en las calles de Nueva York, a menudo disfrutados con mostaza o salsa de queso.",
      TRAJE_TIPICO: 'Estilo vaquero: El estilo vaquero es sinónimo de robustez y practicidad. Típicamente, incluye elementos como un sombrero de vaquero de ala ancha, una camisa de cuadros o de mezclilla, un cinturón de cuero con una gran hebilla, jeans de mezclilla resistentes y botas de vaquero. Los accesorios a menudo incluyen un pañuelo y, a veces, espuelas. Este estilo está profundamente arraigado en la historia del Oeste americano y todavía se celebra en rodeos y escenas de música country. Estilo urbano en Nueva York: El estilo urbano en Nueva York es diverso y en constante evolución, reflejando la cultura dinámica y ecléctica de la ciudad. Los elementos comunes incluyen zapatillas de diseñador, jeans ajustados, camisetas con gráficos, sudaderas con capucha y chaquetas de cuero o mezclilla. Los accesorios a menudo incluyen gafas de sol elegantes, gorras y varias formas de joyería de moda urbana. Este estilo está influenciado por la cultura hip-hop, la alta moda y la vibrante vida callejera de la ciudad, convirtiéndolo en una mezcla única de comodidad y alta moda.',
      PERSONAJES_SOBRESALIENTES: 'Walt Whitman: Fue un poeta, ensayista y periodista estadounidense, considerado uno de los escritores más influyentes de la literatura estadounidense. Su obra más famosa es "Hojas de hierba". Henry James: Fue un novelista y crítico literario estadounidense-británico, conocido por obras como "Retrato de una dama" y "Otra vuelta de tuerca". Robert De Niro: Es un actor, director y productor estadounidense, célebre por sus papeles en películas como "Taxi Driver", "El Padrino II" y "Toro Salvaje". Al Pacino: Es un actor y director estadounidense, conocido por sus interpretaciones en películas como "El Padrino", "Scarface" y "Esencia de mujer". Sojourner Truth: Fue una abolicionista y defensora de los derechos de las mujeres afroamericana, famosa por su discurso "¿Acaso no soy una mujer?". Bella Abzug: Fue una abogada, congresista y activista social estadounidense, conocida por su lucha por los derechos de las mujeres y los derechos civiles.',      
      MUSICA: "Musica de New York"

      
    }
  }
}


module.exports = languageStrings;
